name: Publish Preview Release
on: [push, pull_request]

jobs:
  build:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/esrap'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm prepublishOnly
      - run: pnpm dlx pkg-pr-new publish --no-template
